// Mocks generated by Mockito 5.4.4 from annotations
// in gain_to_do/test/unit/workout_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gain_to_do/data/models/workout_menu.dart' as _i4;
import 'package:gain_to_do/data/models/workout_session.dart' as _i5;
import 'package:gain_to_do/data/repositories/workout_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutRepository extends _i1.Mock implements _i2.WorkoutRepository {
  MockWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addWorkoutMenu(_i4.WorkoutMenu? menu) => (super.noSuchMethod(
        Invocation.method(
          #addWorkoutMenu,
          [menu],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.WorkoutMenu>> getWorkoutMenus() => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutMenus,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.WorkoutMenu>>.value(<_i4.WorkoutMenu>[]),
      ) as _i3.Future<List<_i4.WorkoutMenu>>);

  @override
  _i3.Future<void> updateWorkoutMenu(_i4.WorkoutMenu? menu) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutMenu,
          [menu],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWorkoutMenu(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkoutMenu,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveWorkoutSession(_i5.WorkoutSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkoutSession,
          [session],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.WorkoutSession>> getWorkoutHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutHistory,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.WorkoutSession>>.value(<_i5.WorkoutSession>[]),
      ) as _i3.Future<List<_i5.WorkoutSession>>);

  @override
  _i3.Future<_i5.WorkoutSession?> getWorkoutSession(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSession,
          [id],
        ),
        returnValue: _i3.Future<_i5.WorkoutSession?>.value(),
      ) as _i3.Future<_i5.WorkoutSession?>);

  @override
  _i3.Future<List<_i5.WorkoutSession>> getSessionsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsByDateRange,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i3.Future<List<_i5.WorkoutSession>>.value(<_i5.WorkoutSession>[]),
      ) as _i3.Future<List<_i5.WorkoutSession>>);
}
